### ISSUE TITLE
confusing file name

### ISSUE THREAD

**Issue by abrahammartin** [uisautomation/lecture-capture-agent-ansible#65]
in the readme we say
``vault view lecture-capture-deploy-main > ~/.ssh/lecture-capture-deploy-main``

The name lecture-capture-deploy-main is confusing as we already have lecture-capture-backend-deploy-main, this should be named lecture-capture-agent-deploy-main

**Comment by rjw57** [comment]
Maybe we should just copy the agent deploy secrets out of uisautomation/docs and put them in this repo. We can fix up the naming along the way.

**Comment by rjw57** [comment]
Also, the README has the wrong name of the passphrase file. s/lecture-capture-deploy.passphrase/lecture-capture-deploy-main.passphrase/
